rank: "0"
exp_name: 'pe_gt20_h'
exp_mode: 's2s'
resume_last: false
resume_best: false
logs_folder: './logs/'
test: false

topk: 20
gt_infer: true

optimizer:
  batch_size: 32
  num_workers: 4
  lr: 0.0001
  factor: 0.5
  patience: 3

dataset:
  root_path: '../mscoco'
  use_cache: true
  vocab_path: '../mscoco/txt/coco_vocabulary.txt'
  transform:
    size: [384, 640] # (h, w)
    resize_name: maxwh # normal, minmax, maxwh; maxwh is computationally friendly for training
    randaug: True