rank: "1"
exp_name: 'eed_pe_gen20_sorted_mse_newwordemb'
exp_mode: 's2s'
resume_last: false
resume_best: false
logs_folder: './logs/'
test: false

topk: 20
gt_infer: false

loss:
  alpha: 0.5
  gammaT: 0
  gammaF: 1
  weighted: false

optimizer:
  batch_size: 32
  num_workers: 4
  lr: 0.0001
  factor: 0.5
  patience: 3

dataset:
  root_path: '../mscoco'
  use_cache: true
  vocab_path: '../mscoco/txt/coco_vocabulary.txt'
  transform:
    size: [384, 640] # (h, w)
    resize_name: maxwh # normal, minmax, maxwh; maxwh is computationally friendly for training
    randaug: True