exp_name: '0425'
mode: 's2sw'
resume_last: false
resume_best: false
logs_folder: './ckpts/logs/'

optimizer:
  batch_size: 32
  num_workers: 4

dataset:
  root_path: '../mscoco'
  use_cache: true
  vocab_path: '../mscoco/txt/coco_vocabulary.txt'
  transform:
    size: [384, 640] # (h, w)
    resize_name: maxwh # normal, minmax, maxwh; maxwh is computationally friendly for training
    randaug: True