rank: "2"
exp_name: 'weighted_focal_loss_alpha0.1_gamma2'
mode: 's2s_word'
resume_last: false
resume_best: false
logs_folder: './ckpts/logs/'

optimizer:
  batch_size: 32
  num_workers: 8
  lr: 0.0001
  min_lr: 1e-6
  t_max: 20
  gamma: 0.95

dataset:
  root_path: '../mscoco'
  use_cache: true
  vocab_path: '../mscoco/txt/coco_vocabulary.txt'
  transform:
    size: [384, 640] # (h, w)
    resize_name: maxwh # normal, minmax, maxwh; maxwh is computationally friendly for training
    randaug: True